// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Gw_kK05_siYE6iTmGaRaCqHbOSO1WCg',
    appId: '1:268800801627:web:124e78f71c20b3e005787e',
    messagingSenderId: '268800801627',
    projectId: 'wantedloa',
    authDomain: 'wantedloa.firebaseapp.com',
    storageBucket: 'wantedloa.firebasestorage.app',
    measurementId: 'G-MNBGZLN052',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ4x5U5LpokGd7kDBmpoupt3YXYb11abM',
    appId: '1:268800801627:android:f5db8db5c1ffe3d405787e',
    messagingSenderId: '268800801627',
    projectId: 'wantedloa',
    storageBucket: 'wantedloa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQJBPtzXRvpcz-dwW1AQLRQqfwvmw27Q',
    appId: '1:268800801627:ios:198699f26e1a99e405787e',
    messagingSenderId: '268800801627',
    projectId: 'wantedloa',
    storageBucket: 'wantedloa.firebasestorage.app',
    iosBundleId: 'com.example.loapetition',
  );
}
